version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python -m pip install --upgrade pip
      -  pip install pytest
  build:
    commands:
      - echo "Running tests"
  post_build:
    commands:
      - echo "Build completed on `date`"

