version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests"
      - pytest tests/
      - echo "Linting code"
      - pylint app/
  post_build:
    commands:
      - echo "Build completed on `date`"

